### ISSUE TITLE
Let collaborate to keep it up

### ISSUE THREAD

**Issue by cyrilchapon** [KaiSpencer/shopify-app-template-node-ts#1]
Hi,

I'm highly interested in this. I gave this a shot from scratch on my own repo this weekend. Actually spent like 10 hours debugging the crap.

I'll digg into this, test it and probably improve stuff.

**Comment by cyrilchapon** [comment]
Next step could be reimplentation of this idea : https://github.com/Shopify/shopify-app-template-node/issues/1183

Which is pretty simple and much cleaner

**Comment by KaiSpencer** [comment]
Hi @cyrilchapon,

Sounds great! Thank you for taking the interest.
:)
