### ISSUE TITLE
Separate backend and frontend ?

### ISSUE THREAD

**Issue by cyrilchapon** [KaiSpencer/shopify-app-template-node-ts#6]
I came accross that interesting suggestion https://github.com/Shopify/shopify-app-template-node/issues/1183 , and gave it a shot here. I made a first conceptual implementation here : https://github.com/cyrilchapon/shopify-app-template-node-ts/tree/separate-frontend-backend.

(Working in dev mode, untested production build).

What do you think ?

**Comment by KaiSpencer** [comment]
Given the current structure is how the CLIv3 creates an app (especially for use with checkout extensions), how might this look? 
I don't want to deviate from the current structure, but appreciate this is a way some people like to build apps. 

New repo?

**Comment by cyrilchapon** [comment]
Nah I guess you're right. Let's watch https://github.com/Shopify/shopify-app-template-node/issues/1183 as core contributors upvoted this; and integrate that work if that gets merged once.

That's not an emergency by any means.

**Comment by KaiSpencer** [comment]
Sure @cyrilchapon, for now im going to close this issue :)
